default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5

development:
  <<: *default
  database: baukis_development
  username: root
  password:
  host: 127.0.0.1
  port: 3306

test:
  <<: *default
  database: baukis_test
  username: root
  password:
  host: 127.0.0.1
  port: 3306

production:
  <<: *default
  database: baukis_production
  username: root
  password:
  host: 127.0.0.1
  port: 3306
